# Generated by Django 6.1 on 2026-08-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_category_alter_genre_options_genre_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movievideo',
            name='file_format',
            field=models.CharField(default='mp4', max_length=20),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
