# Generated by Django 6.1 on 2026-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movievideo_file_format_movievideo_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
