# Generated by Django 6.1 on 2026-08-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemedia',
            name='movie_storage_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
