# Generated by Django 6.1 on 2026-08-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_remove_permanentdownload_downloaded_at_and_more'),
        ('movies', '0004_movie_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='download',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='permanentdownload',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='permanentdownload',
            name='unique_user_movie_download',
        ),
        migrations.RenameField(
            model_name='permanentdownload',
            old_name='download_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='permanentdownload',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permanentdownload',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_downloads', to='movies.movie'),
        ),
        migrations.AddConstraint(
            model_name='permanentdownload',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_permanent_movie_owner'),
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.RemoveField(
            model_name='permanentdownload',
            name='is_available',
        ),
    ]
