# Generated by Django 6.1 on 2026-09-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('purchases', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.purchase'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionorder'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('purchase__isnull', True)), models.Q(('order__isnull', True), ('purchase__isnull', False)), _connector='OR'), name='payment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('status__in', ['PENDING', 'PROCESSING'])), fields=('order',), name='unique_active_payment_per_order'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase__isnull', False), ('status__in', ['PENDING', 'PROCESSING'])), fields=('purchase',), name='unique_active_payment_per_purchase'),
        ),
    ]
